# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-11 11:00

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_suppliers", "0001_initial"),
        ("django_suppliers", "0002_supplierfeed_importlog_integrationevent_feed_and_more"),
        ("django_suppliers", "0003_alter_integrationevent_event_type_and_more"),
        ("django_suppliers", "0004_push_pipeline"),
        ("django_suppliers", "0005_product_supplier_link"),
        ("django_suppliers", "0006_event_type_scraper_choices"),
        ("django_suppliers", "0007_supplier_product_change_log"),
        ("django_suppliers", "0008_alter_changelog_source_add_operator_ack"),
        ("django_suppliers", "0009_etap_08_language_fallback"),
        ("django_suppliers", "0010_etap_09_mapping_modifier"),
        ("django_suppliers", "0011_supplier_default_product_class"),
        ("django_suppliers", "0012_importlog_pushed_delisted_fields"),
        ("django_suppliers", "0013_etap_13a_ean_match"),
        ("django_suppliers", "0014_etap_13b_preferred_strategy"),
        ("django_suppliers", "0015_etap_07b_merge_enums"),
        ("django_suppliers", "0016_etap_10_physical_race_detection"),
        ("django_suppliers", "0017_etap_10_importlog_physical_counts"),
    ]

    # Data ops from the old chain intentionally not carried over (no-op on a fresh database):
    # 0011_supplier_default_product_class backfilled default_product_class=1 on pre-existing
    # Supplier rows; the field default already covers fresh installations.

    dependencies = [
        ("django_pim", "0001_squashed_0060_productattribute_nulls_not_distinct"),
        ("django_regional", "0002_reset_pk_sequences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("auto_push_enabled", models.BooleanField(default=True)),
                ("scraper_dispatch_enabled", models.BooleanField(default=True)),
                ("delta_sync_enabled", models.BooleanField(default=True)),
                ("integration_event_retention_days", models.PositiveIntegerField(default=90)),
                ("change_log_retention_days", models.PositiveIntegerField(default=90)),
            ],
            options={
                "verbose_name": "Supplier Settings",
                "verbose_name_plural": "Supplier Settings",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "supplier_role",
                    models.CharField(
                        choices=[("trade", "Trade"), ("data", "Data"), ("monitoring", "Monitoring")],
                        default="trade",
                        max_length=20,
                    ),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[("feed", "Feed"), ("manual", "Manual"), ("dropship", "Dropship")],
                        default="feed",
                        max_length=20,
                    ),
                ),
                (
                    "review_mode",
                    models.CharField(choices=[("manual", "Manual"), ("auto", "Auto")], default="manual", max_length=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sku_prefix", models.CharField(default="", max_length=10)),
                ("default_feature_set_idx", models.CharField(blank=True, max_length=64, null=True)),
                ("target_warehouse_code", models.CharField(blank=True, max_length=64, null=True)),
                ("default_product_class", models.PositiveSmallIntegerField(default=1)),
                (
                    "realproduct_match_tolerance_pct",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Max acceptable per-field diff (%) when EAN-matching an existing RealProduct.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "realproduct_match_strict",
                    models.BooleanField(
                        default=False,
                        help_text="When True, missing physical field on either side fails tolerance (no skip).",
                    ),
                ),
                (
                    "disable_ean_auto_link",
                    models.BooleanField(
                        default=False,
                        help_text="When True, init push never tries EAN-based RealProduct lookup (per-supplier opt-out).",
                    ),
                ),
                (
                    "allow_physical_writes_from_non_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="When True, this supplier's delta sync may overwrite RealProduct physical fields (weight, ean, width, height, deep) even if its link is not preferred. Default False — preferred is the single source of truth. Opt-in only for vendor-tested measurement use cases (audited as physical_update_overwrite warning event).",
                    ),
                ),
                (
                    "preferred_strategy",
                    models.CharField(
                        choices=[
                            ("lowest_cost_with_stock", "Lowest cost with stock"),
                            ("highest_stock", "Highest stock"),
                            ("manual_only", "Manual only"),
                        ],
                        default="lowest_cost_with_stock",
                        help_text="Picker strategy for auto-preferred evaluation across this supplier's links.",
                        max_length=32,
                    ),
                ),
                (
                    "preferred_switch_cooldown_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Minimum hours between consecutive auto-preferred switches on the same RealProduct.",
                    ),
                ),
                (
                    "preferred_switch_hysteresis_pct",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Minimum cost-improvement (%) required before auto-preferred swaps the winner.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "eval_frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("hourly", "Hourly"), ("manual", "Manual")],
                        default="daily",
                        help_text="How often the auto-preferred cron evaluates this supplier's RealProducts.",
                        max_length=16,
                    ),
                ),
                (
                    "qty_subtract",
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    "qty_minimum",
                    models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
                ),
                ("company_name", models.CharField(blank=True, default="", max_length=128)),
                ("contact_email", models.EmailField(blank=True, default="", max_length=254)),
                ("contact_phone", models.CharField(blank=True, default="", max_length=32)),
                ("contact_person", models.CharField(blank=True, default="", max_length=128)),
                ("notes", models.TextField(blank=True, default="")),
                ("lead_time_days", models.IntegerField(blank=True, null=True)),
                ("credentials", models.JSONField(blank=True, default=dict)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_regional.country",
                    ),
                ),
                (
                    "default_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="django_regional.currency"
                    ),
                ),
                (
                    "default_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="django_regional.language"
                    ),
                ),
            ],
            options={
                "ordering": ["idx"],
            },
        ),
        migrations.CreateModel(
            name="ProductSupplierLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("real_product_sku", models.CharField(db_index=True, max_length=128)),
                ("external_id", models.CharField(blank=True, default="", max_length=128)),
                ("priority", models.IntegerField(default=0)),
                ("is_preferred", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "manual_override",
                    models.BooleanField(
                        default=False,
                        help_text="When True, auto-preferred cron skips this link's RealProduct. Cleared by reset-to-auto.",
                    ),
                ),
                (
                    "preferred_changed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last is_preferred=True flip. Used for cooldown check.",
                        null=True,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="django_suppliers.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierFeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.SlugField(max_length=64)),
                ("connector_kind", models.CharField(max_length=64)),
                ("feed_config", models.JSONField(blank=True, default=dict)),
                ("schedule_cron", models.CharField(blank=True, default="", max_length=64)),
                (
                    "sync_mode",
                    models.CharField(choices=[("full", "Full"), ("delta", "Delta")], default="full", max_length=10),
                ),
                ("feature_set_idx", models.CharField(blank=True, max_length=64, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(blank=True, default="", max_length=20)),
                ("last_run_id", models.UUIDField(blank=True, default=None, null=True)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_regional.currency",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_regional.language",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeds",
                        to="django_suppliers.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("run_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "mode",
                    models.CharField(choices=[("full", "Full"), ("delta", "Delta"), ("test", "Test")], max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("new_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("unchanged_count", models.PositiveIntegerField(default=0)),
                ("delisted_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("pushed_delisted_count", models.PositiveIntegerField(default=0)),
                ("mass_delisting_triggered", models.BooleanField(default=False)),
                ("physical_updated_count", models.PositiveIntegerField(default=0)),
                ("physical_skipped_non_preferred_count", models.PositiveIntegerField(default=0)),
                ("physical_overwrite_count", models.PositiveIntegerField(default=0)),
                ("error_summary", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(
                        choices=[("cli", "CLI"), ("api", "API"), ("scheduler", "Scheduler"), ("signal", "Signal")],
                        max_length=10,
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_logs",
                        to="django_suppliers.supplierfeed",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierMappingProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("target_channel_idxs", models.JSONField(blank=True, default=list)),
                ("feature_set_idx", models.CharField(blank=True, max_length=64, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "import_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="django_regional.language",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_profiles",
                        to="django_suppliers.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierCategoryMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("source_field", models.CharField(max_length=128)),
                ("source_value", models.CharField(max_length=512)),
                ("target_category_idx", models.CharField(max_length=64)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_mappings",
                        to="django_suppliers.suppliermappingprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierAttributeMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("source_field", models.CharField(max_length=128)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("feature", "Feature"), ("real_product", "Real product"), ("skip", "Skip")],
                        max_length=20,
                    ),
                ),
                ("target_identifier", models.CharField(blank=True, default="", max_length=128)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "modifier",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("grams_to_kg", "Grams -> kg (/1000)"),
                            ("kg_to_grams", "Kg -> grams (x1000)"),
                            ("mm_to_cm", "mm -> cm (/10)"),
                            ("cm_to_mm", "cm -> mm (x10)"),
                            ("mm_to_m", "mm -> m (/1000)"),
                            ("currency_minor_to_major", "Currency minor -> major (/100)"),
                            ("currency_major_to_minor", "Currency major -> minor (x100)"),
                            ("string_trim", "String trim"),
                            ("string_lowercase", "String lowercase"),
                            ("string_uppercase", "String uppercase"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_mappings",
                        to="django_suppliers.suppliermappingprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(db_index=True, max_length=128)),
                ("external_id_history", models.JSONField(blank=True, default=list)),
                ("name", models.CharField(db_index=True, max_length=512)),
                ("cost", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                ("stock", models.IntegerField(blank=True, null=True)),
                ("ean", models.CharField(blank=True, db_index=True, default="", max_length=14)),
                ("url", models.URLField(blank=True, default="", max_length=2048)),
                ("image_urls", models.JSONField(blank=True, default=list)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("data_hash", models.CharField(blank=True, db_index=True, default="", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("queued", "Queued"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pushed_pending_images", "Pushed (pending images)"),
                            ("pushed", "Pushed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=30,
                    ),
                ),
                ("feature_set_idx_override", models.CharField(blank=True, max_length=64, null=True)),
                ("pushed_to_channel_idxs", models.JSONField(blank=True, default=list)),
                ("images_complete_channel_idxs", models.JSONField(blank=True, default=list)),
                ("last_synced_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("data_changed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("physical_changed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="django_suppliers.supplierfeed",
                    ),
                ),
                (
                    "pushed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "real_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_products",
                        to="django_pim.realproduct",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="django_suppliers.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("feed_failed", "Feed failed"),
                            ("scraper_banned", "Scraper banned"),
                            ("scraper_dispatch_skipped", "Scraper dispatch skipped"),
                            ("image_failed", "Image failed"),
                            ("push_failed", "Push failed"),
                            ("push_succeeded", "Push succeeded"),
                            ("cost_updated", "Cost updated"),
                            ("mass_delisting", "Mass delisting"),
                            ("feed_no_run", "Feed no run"),
                            ("pim_feature_missing", "PIM feature missing"),
                            ("qms_not_installed_skipped", "QMS not installed (skipped)"),
                            ("qms_warehouse_not_configured", "QMS warehouse not configured"),
                            ("qms_write_failed", "QMS write failed"),
                            ("pushed_product_delisted", "Pushed product delisted"),
                            ("ean_collision_detected", "EAN collision detected"),
                            ("unknown_external_id_in_delta", "Unknown external_id in delta"),
                            ("physical_update_applied", "Physical update applied"),
                            ("force_repush_executed", "Force re-push executed"),
                            ("import_completed", "Import completed"),
                            ("supplier_deleted", "Supplier deleted"),
                            ("channel_removed_from_profile", "Channel removed from profile"),
                            ("attribute_value_missing", "Attribute value missing"),
                            ("pim_attribute_missing", "PIM attribute missing"),
                            ("pim_category_missing", "PIM category missing"),
                            ("pim_feature_set_missing", "PIM feature_set missing"),
                            ("pim_channel_missing", "PIM channel missing"),
                            ("image_download_started", "Image download started"),
                            ("image_download_completed", "Image download completed"),
                            ("multi_supplier_overlap", "Multi-supplier overlap"),
                            ("stock_updated", "Stock updated"),
                            ("qms_no_real_product", "QMS no real_product"),
                            ("cost_missing", "Cost missing"),
                            ("currency_missing", "Currency missing"),
                            ("scraper_results_validation_errors", "Scraper results validation errors"),
                            ("scraper_unknown_run_id", "Scraper unknown run_id"),
                            ("scraper_callback_signature_invalid", "Scraper callback signature invalid"),
                            ("supplier_credentials_viewed", "Supplier credentials viewed"),
                            ("language_fallback", "Language fallback"),
                            ("mapping_transform_failed", "Mapping transform failed"),
                            ("auto_linked_to_existing_realproduct", "Auto-linked to existing RealProduct"),
                            ("physical_tolerance_violation", "Physical tolerance violation"),
                            ("manual_unlink_from_realproduct", "Manual unlink from RealProduct"),
                            ("preferred_supplier_switched", "Preferred supplier switched"),
                            ("preferred_supplier_emergency_switch", "Preferred supplier emergency switch"),
                            ("preferred_supplier_forced", "Preferred supplier forced (manual override)"),
                            ("preferred_switch_skipped_cooldown", "Preferred switch skipped (cooldown)"),
                            ("preferred_switch_skipped_hysteresis", "Preferred switch skipped (hysteresis)"),
                            ("preferred_switch_skipped_manual_override", "Preferred switch skipped (manual override)"),
                            ("realproduct_manually_merged", "RealProduct manually merged"),
                            ("physical_update_skipped_non_preferred", "Physical update skipped (non-preferred)"),
                            ("physical_update_overwrite", "Physical update overwrite (opt-in non-preferred)"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "Critical"), ("warning", "Warning"), ("info", "Info")], max_length=10
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="django_suppliers.supplier",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_events",
                        to="django_suppliers.supplierfeed",
                    ),
                ),
                (
                    "supplier_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_events",
                        to="django_suppliers.supplierproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierProductChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("real_product_sku", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("full_sync", "Full sync"),
                            ("delta_sync", "Delta sync"),
                            ("init_push", "Init push"),
                            ("force_repush", "Force re-push"),
                            ("operator_sp_edit", "Operator SP edit"),
                            ("auto_link", "Auto EAN link"),
                            ("auto_preferred_switch", "Auto preferred switch"),
                            ("manual_override", "Manual override"),
                            ("emergency_switch", "Emergency switch"),
                            ("operator_acknowledge", "Operator acknowledge"),
                            ("language_fallback", "Language fallback"),
                            ("mapping_transform", "Mapping transform"),
                            ("cost_signal_received", "Cost signal received"),
                            ("cost_ignored_non_preferred", "Cost ignored (non-preferred)"),
                            ("cost_ignored_no_link", "Cost ignored (no link)"),
                            ("cost_skipped_admin_override", "Cost skipped (admin override)"),
                            ("cost_skipped_resolution_failed", "Cost skipped (resolution failed)"),
                            ("manual_unlink", "Manual unlink from RealProduct"),
                            ("manual_merge", "Manual merge by EAN"),
                            ("physical_skipped", "Physical skipped (non-preferred)"),
                            ("physical_overwrite", "Physical overwrite (opt-in)"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("field_path", models.CharField(db_index=True, max_length=128)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("applied_to_pim", models.BooleanField(default=False)),
                ("applied_to_pim_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supplier_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="django_suppliers.supplierproduct",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["idx"], name="django_supp_idx_ab832d_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["is_active"], name="django_supp_is_acti_8364b3_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["supplier_role"], name="django_supp_supplie_6dce78_idx"),
        ),
        migrations.AddIndex(
            model_name="productsupplierlink",
            index=models.Index(fields=["real_product_sku"], name="django_supp_real_pr_7ee159_idx"),
        ),
        migrations.AddIndex(
            model_name="productsupplierlink",
            index=models.Index(fields=["supplier"], name="django_supp_supplie_8f0b22_idx"),
        ),
        migrations.AddIndex(
            model_name="productsupplierlink",
            index=models.Index(fields=["manual_override"], name="django_supp_manual__8c1ca6_idx"),
        ),
        migrations.AddConstraint(
            model_name="productsupplierlink",
            constraint=models.UniqueConstraint(
                fields=("real_product_sku", "supplier"), name="uq_productsupplierlink_sku_supplier"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierfeed",
            index=models.Index(fields=["supplier", "is_active"], name="django_supp_supplie_21ba33_idx"),
        ),
        migrations.AddConstraint(
            model_name="supplierfeed",
            constraint=models.UniqueConstraint(fields=("supplier", "idx"), name="uq_supplierfeed_supplier_idx"),
        ),
        migrations.AddIndex(
            model_name="suppliermappingprofile",
            index=models.Index(fields=["supplier", "is_active"], name="django_supp_supplie_af64df_idx"),
        ),
        migrations.AddConstraint(
            model_name="suppliermappingprofile",
            constraint=models.UniqueConstraint(
                fields=("supplier", "idx"), name="uq_suppliermappingprofile_supplier_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliercategorymapping",
            constraint=models.UniqueConstraint(
                fields=("profile", "source_field", "source_value"),
                name="uq_suppliercategorymapping_profile_source_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierattributemapping",
            constraint=models.UniqueConstraint(
                fields=("profile", "source_field"), name="uq_supplierattributemapping_profile_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierproduct",
            constraint=models.UniqueConstraint(
                fields=("supplier", "external_id"), name="uq_supplierproduct_supplier_external"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationevent",
            index=models.Index(fields=["event_type", "severity"], name="django_supp_event_t_3b8055_idx"),
        ),
        migrations.AddIndex(
            model_name="integrationevent",
            index=models.Index(fields=["-created_at"], name="django_supp_created_6c74db_idx"),
        ),
        migrations.AddIndex(
            model_name="integrationevent",
            index=models.Index(fields=["acknowledged_at"], name="django_supp_acknowl_d80f5b_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierproductchangelog",
            index=models.Index(fields=["supplier_product", "-created_at"], name="supp_changelog_sp_created_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierproductchangelog",
            index=models.Index(
                fields=["real_product_sku", "applied_to_pim", "-created_at"], name="supp_changelog_sku_unseen_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproductchangelog",
            index=models.Index(fields=["source", "-created_at"], name="supp_changelog_source_idx"),
        ),
    ]
